set shell          := ["bash", "-c"]
set dotenv-load    := true
export SERVER_PORT := env_var_or_default("SERVER_PORT", "3000")
export APP_FQDN    := env_var_or_default("APP_FQDN", "framejs-io.localhost")

@_help:
    just --list --unsorted

dev:
    deno run --allow-all HTTPS://deno.land/x/metapages@v0.0.17/exec/open_url.ts https://metapages.github.io/load-page-when-available/?url=http://${APP_FQDN}:${SERVER_PORT}
    DEV=true PORT={{SERVER_PORT}} APP_FQDN={{APP_FQDN}} deno run --watch -A ./server.ts
    
# Format TypeScript
@fmt:
    deno fmt .

# Quick type check
@check:
    deno check server.ts
    echo "✅ worker typescript compilation"

# Type check plus unit tests
test: check
    deno test --allow-all src/
    echo "✅ worker unit tests"